name: camera_riverpod_flutter
description: Camera access on Flutter using Riverpod and MVU architecture.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.3
  flutter:
    sdk: flutter

dev_dependencies:

  camera: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_riverpod: ^1.0.4

  path_provider:
  path:

  flutter_test:
    sdk: flutter

  riverpod: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - assets/img.png
